apiVersion: v1
kind: Service
metadata:
  labels:
    app: joel-was
  name: joel-was-svc
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: joel-was # 그 라벨을 가진 포드를 찾아갑니다
  type: ClusterIP # 클러스터 내부에서만 볼수있도록 구현